name: Build, Test, and Publish

on:
    pull_request:
        types: [opened, synchronize]
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    lint-format-and-static-code-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: 3.8
            - name: Install pre-commit
              run: pip install pre-commit
            - name: Lint, Format, and Static Code Quality Checks
              run: |
                /bin/bash -x run.sh lint:ci

    execute-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: 3.8
            - name: Install test dependencies
              run: pip install cookiecutter pytest pytest-cov
            - name: Run tests
              run: |
                /bin/bash -x run.sh run-tests
