name: Create or Update Repo

on:
    workflow_dispatch:
        inputs:
            repo_name:
                description: 'Name of the Repo to Create.'
                required: true
                type: string
            repo_visibility:
                description: 'If unchecked, Repo is Private.'
                required: true
                default: false
                type: boolean
            repo_description:
                description: 'Repo Description. If not provided, default is used.'
                required: false
                default: 'This is a generated repository using the `python-cookiecutter-template`.'
                type: string
            package_import_name:
                description: 'Package Import Name, used in generated project. E.g., `from <pkg_name> import <module_name>`'
                required: true
                type: string

env:
    GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

jobs:
    create-repository-if-not-exists:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Create Repo if not exists
              env:
                REPO_NAME: ${{ github.event.inputs.repo_name }}
                GITHUB_USERNAME: avr2002
                IS_PUBLIC_REPO: ${{ github.event.inputs.repo_visibility }}
                REPO_DESCRIPTION: ${{ github.event.inputs.repo_description }}
              run: |
                bash run.sh create-repository-if-not-exists

    configure-repository:
        needs:
            - create-repository-if-not-exists
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Configure Repository
              env:
                REPO_NAME: ${{ github.event.inputs.repo_name }}
                GITHUB_USERNAME: avr2002
                TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
                PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
              run: |
                bash run.sh configure-repository

    open-pull-request-with-generated-project:
        needs:
            - create-repository-if-not-exists
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Open Pull Request
              env:
                REPO_NAME: ${{ github.event.inputs.repo_name }}
                GITHUB_USERNAME: avr2002
                PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package_import_name }}
              run: |
                bash run.sh open-pull-request-with-generated-project
